"""
report_generator.py

Builds a clean, structured PDF report from the case data collected
through the form. This is the "wow" piece of the demo — a messy
report becomes a professional document in seconds.

Note: every text block below uses an explicit width (pdf.epw, the
"effective page width") rather than the fpdf shortcut width=0. This
avoids a real fpdf2 edge case where 0-width cells/multi_cells can
raise "Not enough horizontal space" if the cursor x position isn't
exactly at the left margin when they're called.
"""

import os
from datetime import datetime
from fpdf import FPDF, XPos, YPos

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "sample_output")


class ReportPDF(FPDF):
    def header(self):
        self.set_x(self.l_margin)
        self.set_font("Helvetica", "B", 14)
        self.cell(self.epw, 10, "Online Abuse Incident Report",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.set_x(self.l_margin)
        self.set_font("Helvetica", "", 9)
        self.cell(self.epw, 6, "Generated by SheCommits2Grow",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_x(self.l_margin)
        self.set_font("Helvetica", "I", 8)
        self.cell(self.epw, 10, f"Page {self.page_no()}", align="C")


def _reset_x(pdf: ReportPDF):
    """Always call before a new text block, so width calculations are predictable."""
    pdf.set_x(pdf.l_margin)


def _section_title(pdf: ReportPDF, title: str):
    _reset_x(pdf)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(pdf.epw, 8, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
    pdf.ln(1)


def _field(pdf: ReportPDF, label: str, value: str):
    _reset_x(pdf)
    text = f"{label}: {value if value else '-'}"
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(pdf.epw, 7, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def _line(pdf: ReportPDF, text: str, bold: bool = False):
    _reset_x(pdf)
    pdf.set_font("Helvetica", "B" if bold else "", 10)
    pdf.multi_cell(pdf.epw, 7, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def generate_report(case: dict, image_check: dict, guidance: dict) -> str:
    """
    case: {
        "reporter_name": str (optional, can be "Anonymous"),
        "platform": str,
        "incident_date": str,
        "incident_type_label": str,
        "description": str,
    }
    image_check: output of metadata_check.check_image()
    guidance: output of routing_logic.get_guidance()

    Returns the file path of the generated PDF.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    pdf = ReportPDF()
    pdf.add_page()

    _section_title(pdf, "Report Details")
    _field(pdf, "Generated", datetime.now().strftime("%Y-%m-%d %H:%M"))
    _field(pdf, "Reporter", case.get("reporter_name") or "Anonymous")
    _field(pdf, "Platform", case.get("platform", ""))
    _field(pdf, "Incident date", case.get("incident_date", ""))
    _field(pdf, "Incident type", case.get("incident_type_label", ""))
    pdf.ln(2)

    _section_title(pdf, "Description")
    _line(pdf, case.get("description", "-"))
    pdf.ln(2)

    _section_title(pdf, "Evidence Check")
    _line(pdf, f"File: {image_check.get('filename', '-')}")
    _line(pdf, f"Dimensions: {image_check.get('dimensions', '-')}")
    _line(pdf, f"EXIF metadata present: {image_check.get('has_exif', False)}")
    if image_check.get("warnings"):
        _line(pdf, "Warnings:", bold=True)
        for w in image_check["warnings"]:
            _line(pdf, f"- {w}")
    pdf.ln(2)

    _section_title(pdf, f"Recommended Next Steps (Urgency: {guidance.get('urgency', 'medium').upper()})")
    for i, step in enumerate(guidance.get("steps", []), start=1):
        _line(pdf, f"{i}. {step}")

    filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    output_path = os.path.join(OUTPUT_DIR, filename)
    pdf.output(output_path)
    return output_path
